### PR TITLE
Tells the user where to go to find more information about the firmware.

### PR DESCRIPTION
**Pull request by spaulaus**
Explicitly points them to the wiki when `-h` is called.

### CODE REVIEW

**Comment by ksmith0** [comment]
This is an improvement. I'd like to see something like `utkscan help firmware` and you get a long message about the firmware choices. The internet is not always available.

**Comment by spaulaus** [comment]
You want us to actually parse those two arguments?

**Comment by ksmith0** [comment]
Yes. I think having something along these lines is extremely useful. We could implement it as an option passed to a flag `utkscan -h firmware`

**Comment by spaulaus** [comment]
The `-h` handling optional arguments might be tricky. I will look into it.

**Comment by spaulaus** [comment]
It looks like the getopts isn't wanting to parse the optional argument properly. I think that if we want to implement something like this, then we're going to have to implement our own class to parse the command line options.

**Comment by spaulaus** [comment]
@ksmith0 , 

I have updated the help output to tell the users that they can locally find the information in HelperEnumerations.hpp. I didn't specify relative path since it would take up too much space. I think that this is as best I can do for now. I tried for an hour and a half to get the long output option working, but ran into a bunch of buggy issues with the getopt_long.

LTS is to write our own class, which we've discussed in the past.

**Comment by ksmith0** [comment]
I appreciate you looking into trying to handle the help arguments. I propose we move this upgrade to an issue and I'll examine this pull request.

**Comment by spaulaus** [comment]
I had to adjust for changes in the directory structure. I wasn't sure how to handle this in the rebase and ended up with an additional commit to move the old file into the new structure.

**Review by ksmith0 — APPROVED** [review]
Works when tested with scope.

**Pull request merged**
