### PR TITLE
Renamed FindPXI to FindXIA

### PR DESCRIPTION
**Pull request by ksmith0**
Also, renamed all PXI variables to XIA.

Also, attempted to resolve Issue #146, but it was too difficult for the time allotted.

### CODE REVIEW

**Review by spaulaus — APPROVED** [review]
I did not find any issues here. 

Tested on 
Linux Flavor: Arch Linux
Kernel : 4.9.7-1-ARCH
cmake : 3.6

**Comment by ksmith0** [comment]
@spaulaus Did you test this on a machine that would attempt to look for the XIA libraries? Did you try `make config`?

**Comment by spaulaus** [comment]
Mine does look for XIA libraries. I didn't test make config. I thought we had set the config to be automatically run with install?

**Comment by ksmith0** [comment]
We did not change `make config` to default. That is issue #55.

**Comment by spaulaus** [comment]
Ah! I just checked and make config is fine. 
```
Scanning dependencies of target config
-- Installing: install/share/config/pixie.cfg
Built target config
```

**Pull request merged**
