### PR TITLE
Refactoring UtkUnpacker to process scalars and histograms

### PR DESCRIPTION
**Pull request by spaulaus**
UtkUnpacker has been refactored to now plot some useful histograms. It also plots scalars for the different channels and provides us with diagnostic outputs and status updates. Most importantly we now have information about the run time and the total number of counts we had per second and per millisecond.

### CODE REVIEW

**Comment by spaulaus** [comment]
@ksmith0 I am once again unable to reproduce the behavior seen on your laptop. We should confirm the cmake cache. 

Its possible that this is due to a misconfigured XML file (there's not a lot of error checking for that unfortunately). There is a configuration file included with this branch called `newhist.xml`. I also have a PLD file that I can pass along that works with that XML, or edit the XML to suit your needs.

**Comment by ksmith0** [comment]
You are referring to the large increase in load and large memory usage (6 GB)? I am making a new DAMM histogram if that makes a difference. The cmake flag is `USE_HRIBF=OFF`

Here is my [CMakeCache.txt](https://github.com/pixie16/paass/files/520011/CMakeCache.txt) and the config file I used [config.xml.txt](https://github.com/pixie16/paass/files/520017/config.xml.txt).

**Comment by ksmith0** [comment]
My earlier issue has been spun off into issue #121. It is a "misconfiguration" in the config file. I will now test this pull request with a working config file.

**Comment by ksmith0** [comment]
The damm histograms were not filled for a set of CeBr3 test files used.

The following message was displayed, but it seems to have no bearing on data output

```
ReadSpill: Received spill of 65569 words, but read 65567 words
ReadSpill: Spill split between buffers 
```

Using `--counts` I see that there were triggered data in M0C0 and M0C1 detected by the unpacker as expected.

**Comment by spaulaus** [comment]
Can you share that file with me so that I can test this? I am in the process of uploading my test data files to OneDrive for ease of sharing.

**Review by ksmith0 — APPROVED** [review]
Works as expected.

**Pull request merged**
