### PR TITLE
Gitignore update

### PR DESCRIPTION
**Pull request by tking53**
I updated the gitignore to exclude the doxywarning.txt file created when generating the Doxygen files. I also updated the doc/doxyfile to exclude the install directory when generating the documentation.

### CODE REVIEW

**Comment by spaulaus** [comment]
Will this also ignore any other variations on the install directory? For example, `install-gitignoreUpdate`, `test-install`, etc.

**Comment by tking53** [comment]
It does not, would you like it too? I was trying to avoid being to general.

**Comment by spaulaus** [comment]
I think in this case we have to be general. We never want the install directory to be found as part of the documentation. The contents of this directory are all contained within the rest of the source trees, which would always result in duplication.

**Review by spaulaus — APPROVED** [review]
The Doxygen build has been updated along with the gitignore.

**Pull request merged**
