### PR TITLE
SCANOR Update for Analysis programs

### PR DESCRIPTION
**Pull request by spaulaus**
I believe this is ready for the development branch. utkscan has been tested with ISOLDE IS599 data, Skeleton and scope have been tested with data from @wapmanzoo's setup simply to see traces and the simple spectrum. All seem to work as expected. 

Some design choices will need to be revisited, but functionally things work.

### CODE REVIEW

**Review by ksmith0 — CHANGES_REQUESTED** [review]
Does not compile!

```
[ 23%] Building CXX object Scan/utkscan/processors/source/CMakeFiles/ProcessorObjects.dir/BetaScintProcessor.cpp.o
In file included from /research/paass/Scan/utkscan/core/include/Plots.hpp:15:0,
                 from /research/paass/Scan/utkscan/core/include/Trace.hpp:19,
                 from /research/paass/Scan/utkscan/core/include/ChanEvent.hpp:14,
                 from /research/paass/Scan/utkscan/core/include/DetectorSummary.hpp:12,
                 from /research/paass/Scan/utkscan/core/include/RawEvent.hpp:23,
                 from /research/paass/Scan/utkscan/processors/source/BetaScintProcessor.cpp:13:
/research/paass/Scan/utkscan/core/include/HisFile.hpp:22:22: fatal error: Scanor.hpp: No such file or directory
compilation terminated.
Scan/utkscan/processors/source/CMakeFiles/ProcessorObjects.dir/build.make:62: recipe for target 'Scan/utkscan/processors/source/CMakeFiles/ProcessorObjects.dir/BetaScintProcessor.cpp.o' failed
make[2]: *** [Scan/utkscan/processors/source/CMakeFiles/ProcessorObjects.dir/BetaScintProcessor.cpp.o] Error 1
CMakeFiles/Makefile2:933: recipe for target 'Scan/utkscan/processors/source/CMakeFiles/ProcessorObjects.dir/all' failed
make[1]: *** [Scan/utkscan/processors/source/CMakeFiles/ProcessorObjects.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by spaulaus** [comment]
I have no problem building on my laptop. I have tested both my main repository, and a fresh download. Neither have issues. Can you post your cmake configuration?

**Comment by ksmith0** [comment]
My comment about not compiling is with the cmake flag `USE_HRIBF=OFF`

**Comment by spaulaus** [comment]
This error has been fixed, along with another error that was identified during testing.

**Review by ksmith0 — APPROVED** [review]
Tested with `USE_HIRBF` and `USE_ROOT` both on and off. All seems to be working.

**Pull request merged**
