### PR TITLE
Resolves Issue 256: Adds a missing ld flag  (-ltinfo)

### PR DESCRIPTION
**Pull request by tking53**
This was needed on the Bill laptop. I would like Miguel to test this. (I cant find his github username in the list). This doesn't seem to break anything on my laptop (ubuntu 16.10 gsl2.3 gcc 6.2)

### CODE REVIEW

**Comment by ksmith0** [comment]
This is related to issue #256. I believe it is an issue with the compiler on that machine and should not be added to the cmake scripts as it should be automatically determined.

**Comment by ksmith0** [comment]
Maybe something along these lines?

```cmake
CHECK_LIBRARY_EXISTS("${CURSES_NCURSES_LIBRARY}"
    cbreak "" CURSES_NCURSES_HAS_CBREAK)
  if(NOT CURSES_NCURSES_HAS_CBREAK)
    find_library(CURSES_EXTRA_LIBRARY tinfo)
    list(APPEND CURSES_LIBRARIES CURSES_EXTRA_LIBRARY)
  endif(NOT CURSES_NCURSES_HAS_CBREAK)
```

**Comment by tking53** [comment]
I have implemented something similar to what @ksmith0 suggested. This works on the BILL laptop and correctly finds the needed library. it still compiles on kqxhc and my ubuntu laptop.

**Comment by tking53** [comment]
i have run into a weird issue. where running just `cmake ../` (with flags for building utkscan and USE_HRIBF) then make does not build however if you use ccmake for the setup it will make without issue. We are currently investigating. Im going to leave this open so we can track the ideas for this.

**Comment by ksmith0** [comment]
I will try to have a look at this tonight.

**Review by spaulaus — COMMENTED** [review]
Since this occurs on only a single platform. I would rather we not include this in the code base.

**Comment by spaulaus** [comment]
I'm closing this request since #256 has been closed as "won't fix". I will leave the branch so that the patch can be viewed if necessary.

**Pull request closed without merging**
