### PR TITLE
Fixing issue #168

### PR DESCRIPTION
**Pull request by spaulaus**
I did some formatting as well. Important changes on line Identifier.hpp:142 and Identifier.cpp:20-21.

### CODE REVIEW

**Comment by ksmith0** [comment]
I don't understand how this resolved the issue, see comment in #168.

**Comment by spaulaus** [comment]
I neglected to stage DetectorDriver.

**Comment by ksmith0** [comment]
All you've done is change the -1 to 9999. You've haven't addressed where the large number is coming from.

**Comment by spaulaus** [comment]
This fixes the bug that was causing the crash. In order to fix the larger issue with the TreeCorrelator and Places requires significantly more work. We can open up a separate issue to refactor these classes, but I do not see the point right now.

**Comment by tking53** [comment]
The patch does allow me to scan one of Steven's ldfs.

**Review by sztaylor89 — APPROVED** [review]
Fixes exceptions when channels aren't defined in the map.  The 9999 default value may cause issues for systems with 10,000 channels.

**Pull request merged**
