### PR TITLE
Merge Dev into Master

### PR DESCRIPTION
**Pull request by spaulaus**
Now that we have settled on a reasonable commit scheme, I believe we should start implementing it. We have used many of the updates in the dev branch for quite a while.

### CODE REVIEW

**Comment by ksmith0** [comment]
According the scheme this merge should be tested for stability. @spaulaus can you confirm this merge is ok for utkscan? @cthornsb do you have any concerns? I have a couple notes of items I wanted to look at first. I'll look tomorrow and post my results.

**Review by ksmith0 — CHANGES_REQUESTED** [review]
Found a bug (#84) that will cause issues on some machines and I think it should be resolved before release.

**Review by spaulaus — COMMENTED** [review]
The issue that @ksmith0 mentioned as problematic [#84](https://github.com/pixie16/paass/issues/84) is an issue with the PLX and XIA APIs. I do not think that we need to fix this issue before pushing to master since we have no control over it.

**Comment by ksmith0** [comment]
Issue #86 is a more serious issue that should be resolved.

**Comment by spaulaus** [comment]
@ksmith0 : I agree.

**Review by ksmith0 — APPROVED** [review]

**Pull request merged**
