### PR TITLE
Merge Release candidate into master

### PR DESCRIPTION
**Pull request by spaulaus**
The RC branch was forked at commit ID 773c297a4c720ef49e49bccf2f5c3dd0dea63e6a. The e14060 branch was also forked from this ID. The experiment ran without any difficulties from the acquisition or analysis side. I do not see any reason that we could not update the master branch to this point.

### CODE REVIEW

**Comment by ksmith0** [comment]
Should I be worried about the test failures?

**Comment by spaulaus** [comment]
Ah, that's shippable. Ignore those failures. I need to remove the integration.

**Comment by ksmith0** [comment]
I will approve this, but I'm not sure what the correct process is here. Do we need to have a group of people testing this? Should we require more than one review?

**Review by ksmith0 — APPROVED** [review]
This should be a reasonable release.

**Comment by spaulaus** [comment]
I think the process would be more straight forward since the RC should only be pushed from dev after the features have undergone testing for a while.

**Pull request merged**
